
FIND_PATH(CURL_INCLUDE_DIR curl/curl.h "$ENV{CURL_ROOT}/include" )

# Look for the library.
FIND_LIBRARY(CURL_LIBRARY_RELEASE NAMES curl  libcurl  PATHS "$ENV{CURL_LIB_DIR}" "$ENV{CURL_ROOT}/lib" )
FIND_LIBRARY(CURL_LIBRARY_DEBUG   NAMES curld libcurld PATHS "$ENV{CURL_LIB_DIR}" "$ENV{CURL_ROOT}/lib" )

CADKIT_SET_DEBUG_RELEASE_LIBRARY( CURL_LIBRARY CURL_LIBRARY_DEBUG CURL_LIBRARY_RELEASE )
